services:
  hub:
    command:
    build:
      context: ./
      dockerfile: Dockerfile
    #image: hub:local
    ports:
    - 8080:8080
    volumes:
    - ~/hub_data:/root/.hub
    restart: on-failure:0
networks:
  default:
    driver: bridge

