---
services:
  hub:
    command:
    build:
      context: ./
      dockerfile: Dockerfile
    image: hub:local
    ports:
    - 8086:8086
    volumes:
    - ~/hub_data:/root/.hub
    restart: on-failure:0
...
