services:
  dimo-hub:
    image: mossv2/dimo:hub-latest
    ports:
      - 8080:8080
    volumes:
      - ~/data:/data
      - ~/.plonk:/root/.plonk
    restart: on-failure:0
    environment:
      EXPOSE_URL: ""
      MAX_SIZE: "4MB"
networks:
  default:
    driver: bridge
