services:
  hub:
    command:
    build:
      context: ../
      dockerfile: Dockerfile
    #image: hub:local
    ports:
      - 8080:8080
    volumes:
      - ~/data/hub:/root/.hub
    restart: on-failure:0
    environment:
      HUB_SIZE: "4MB"
      HUB_EXPOSE: ""
networks:
  default:
    driver: bridge
