// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/conversation": {
            "get": {
                "description": "list all conversations or get conversation messages by conversation id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversation"
                ],
                "summary": "list conversations or get conversation messages by conversation id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "owner/account address",
                        "name": "owner",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "bucket name",
                        "name": "bucket",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "conversation ID (empty means list all conversation ids)",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "pagination offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 32,
                        "description": "number of items per page",
                        "name": "length",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "599": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/error.APIError"
                        }
                    }
                }
            },
            "post": {
                "description": "list all conversations or get conversation messages by conversation id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversation"
                ],
                "summary": "list conversations or get conversation messages by conversation id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "owner/account address",
                        "name": "owner",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "bucket name",
                        "name": "bucket",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "conversation ID (empty means list all conversation ids)",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "pagination offset",
                        "name": "offset",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "default": 32,
                        "description": "number of items per page",
                        "name": "length",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "599": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/error.APIError"
                        }
                    }
                }
            }
        },
        "/api/getAccount": {
            "get": {
                "description": "get account information for a specific owner",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "get account information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "account owner address",
                        "name": "owner",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "599": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/error.APIError"
                        }
                    }
                }
            }
        },
        "/api/getBucket": {
            "get": {
                "description": "get bucket information for a specific bucket",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bucket"
                ],
                "summary": "get bucket information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "account owner address",
                        "name": "owner",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "bucket name",
                        "name": "bucket",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "599": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/error.APIError"
                        }
                    }
                }
            }
        },
        "/api/getConversation": {
            "get": {
                "description": "get detailed information for a specific conversation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversation"
                ],
                "summary": "get conversation details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "owner/account address",
                        "name": "owner",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "bucket name (empty means search in all buckets)",
                        "name": "bucket",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "conversation ID",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Conversation"
                            }
                        }
                    },
                    "599": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/error.APIError"
                        }
                    }
                }
            }
        },
        "/api/getNeedle": {
            "get": {
                "description": "get needle information for a specific owner",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "needle"
                ],
                "summary": "get needle information",
                "parameters": [
                    {
                        "type": "string",
                        "default": "\"\"",
                        "description": "owner address",
                        "name": "owner",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "\"\"",
                        "description": "bucket name",
                        "name": "bucket",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "\"\"",
                        "description": "needle name",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "599": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/error.APIError"
                        }
                    }
                }
            }
        },
        "/api/getVolume": {
            "get": {
                "description": "get volume information for a specific owner",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "volume"
                ],
                "summary": "get volume information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "owner address",
                        "name": "owner",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "file name",
                        "name": "file",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "599": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/error.APIError"
                        }
                    }
                }
            }
        },
        "/api/listAccount": {
            "get": {
                "description": "get a list of accounts with pagination support",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "list accounts",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "pagination offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 32,
                        "description": "number of items per page",
                        "name": "length",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "599": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/error.APIError"
                        }
                    }
                }
            },
            "post": {
                "description": "get a list of accounts with pagination support",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "list accounts",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "pagination offset",
                        "name": "offset",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "default": 32,
                        "description": "number of items per page",
                        "name": "length",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "599": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/error.APIError"
                        }
                    }
                }
            }
        },
        "/api/listBucket": {
            "get": {
                "description": "get a list of buckets with pagination support",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bucket"
                ],
                "summary": "list buckets",
                "parameters": [
                    {
                        "type": "string",
                        "default": "\"\"",
                        "description": "owner address",
                        "name": "owner",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "pagination offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 32,
                        "description": "number of items per page",
                        "name": "length",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "599": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/error.APIError"
                        }
                    }
                }
            },
            "post": {
                "description": "get a list of buckets with pagination support",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bucket"
                ],
                "summary": "list buckets",
                "parameters": [
                    {
                        "type": "string",
                        "description": "owner address",
                        "name": "owner",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "pagination offset",
                        "name": "offset",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "default": 32,
                        "description": "number of items per page",
                        "name": "length",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "599": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/error.APIError"
                        }
                    }
                }
            }
        },
        "/api/listConversation": {
            "get": {
                "description": "list all conversations with detailed information for a specific owner and bucket",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversation"
                ],
                "summary": "list conversations with details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "owner/account address",
                        "name": "owner",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "bucket name (empty means list all conversations of owner)",
                        "name": "bucket",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "pagination offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 32,
                        "description": "number of items per page",
                        "name": "length",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Conversation"
                            }
                        }
                    },
                    "599": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/error.APIError"
                        }
                    }
                }
            }
        },
        "/api/listNeedle": {
            "get": {
                "description": "get a list of needles for a specific owner with pagination support",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "needle"
                ],
                "summary": "list needles",
                "parameters": [
                    {
                        "type": "string",
                        "default": "\"\"",
                        "description": "owner address",
                        "name": "owner",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "\"\"",
                        "description": "bucket name",
                        "name": "bucket",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "pagination offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 32,
                        "description": "number of items per page",
                        "name": "length",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "599": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/error.APIError"
                        }
                    }
                }
            },
            "post": {
                "description": "get a list of needles for a specific owner with pagination support",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "needle"
                ],
                "summary": "list needles",
                "parameters": [
                    {
                        "type": "string",
                        "default": "\"\"",
                        "description": "owner address",
                        "name": "owner",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "default": "\"\"",
                        "description": "bucket name",
                        "name": "bucket",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "pagination offset",
                        "name": "offset",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "default": 32,
                        "description": "number of items per page",
                        "name": "length",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "599": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/error.APIError"
                        }
                    }
                }
            }
        },
        "/api/listVolume": {
            "get": {
                "description": "get a list of volumes for a specific owner with pagination support",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "volume"
                ],
                "summary": "list volumes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "owner address",
                        "name": "owner",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "pagination offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 32,
                        "description": "number of items per page",
                        "name": "length",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "599": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/error.APIError"
                        }
                    }
                }
            },
            "post": {
                "description": "get a list of volumes for a specific owner with pagination support",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "volume"
                ],
                "summary": "list volumes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "owner address",
                        "name": "owner",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "pagination offset",
                        "name": "offset",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "default": 32,
                        "description": "number of items per page",
                        "name": "length",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "599": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/error.APIError"
                        }
                    }
                }
            }
        },
        "/api/stat": {
            "get": {
                "description": "Get daily statistics for accounts, needles, and volumes using GET method",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statistics"
                ],
                "summary": "Get statistics by GET",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of days to return (default: 30)",
                        "name": "count",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Array of daily statistics",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Stat"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid count parameter",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Get daily statistics for accounts, needles, and volumes using POST method",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statistics"
                ],
                "summary": "Get statistics by POST",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of days to return (default: 30)",
                        "name": "count",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Array of daily statistics",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Stat"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid count parameter",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "error.APIError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "types.Conversation": {
            "type": "object",
            "properties": {
                "bucket": {
                    "type": "string"
                },
                "count": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "types.Stat": {
            "type": "object",
            "properties": {
                "dailyAccounts": {
                    "description": "new created accounts at this day",
                    "type": "integer"
                },
                "dailyBuckets": {
                    "description": "new created buckets at this day",
                    "type": "integer"
                },
                "dailyNeedles": {
                    "description": "new created needles at this day",
                    "type": "integer"
                },
                "dailyVolumes": {
                    "description": "new created volumes at this day",
                    "type": "integer"
                },
                "day": {
                    "type": "string"
                },
                "totalAccounts": {
                    "description": "total accounts until this day",
                    "type": "integer"
                },
                "totalBuckets": {
                    "description": "total buckets until this day",
                    "type": "integer"
                },
                "totalNeedles": {
                    "description": "total needles until this day",
                    "type": "integer"
                },
                "totalVolumes": {
                    "description": "total volumes until this day",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "HUB API",
	Description:      "This is a HUB API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
